### ISSUE TITLE
can I popup a ViewController with NavigationBar?

### ISSUE THREAD

**Issue by heyehao2008** [ergunemr/BottomPopup#4]
can I popup a ViewController(named A) with NavigationBar, and use this bar to push another ViewController(named B)
A and B has same height

**Comment by ergunemr** [comment]
Unfortunately you cannot present navigation controller at this time. But I'm adding this feature to todo list and it will be available in next release 👍Thank you

**Comment by heyehao2008** [comment]
awesome!👍

**Comment by ergunemr** [comment]
Hello there, BottomPopupNavigationController is available now. ( with version 0.3.1 )If you want to present navigation controller with navigation bar, in storyboard embed your view controller in a navigation controller. then create a navigation controller subclass and make it super class BottomPopupViewController
Then you can present your navigation controller with default present method. Navigation bar and pushing operations will work fine.
By the way you can look at the example project, i have updated it too.
Inform me if any unexpected behaviour occurs.
@heyehao2008

**Comment by heyehao2008** [comment]
perfect👍
I will use it in my current project.
