### ISSUE TITLE
BottomPopupTransitionHandler memory leak

### ISSUE THREAD

**Issue by alecananian** [ergunemr/BottomPopup#42]
@ergunemr Any plans to release v0.7.1 which includes the memory leak fix in #40? I see the version was updated, but no release/tag has been made, so we can't specify v0.7.1 in Swift Package Manager. Thanks

**Comment by yusufozgul** [comment]
Hi @alecananian sorry for delay. New version has been released.

**Comment by alecananian** [comment]
Awesome, thanks! 🙏
