### ISSUE TITLE
Access Control

### ISSUE THREAD

**Issue by butcheryl** [ergunemr/BottomPopup#6]
https://github.com/ergunemr/BottomPopup/blob/886c3ba4776bfa52674886a968192c3719128adc/BottomPopup/BottomPopupController/BottomPopupViewController.swift#L17

```
override public init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) { 
```

**Comment by ergunemr** [comment]
Duplicate of #5
